# Generated by Django 4.1.7 on 2026-02-11 15:17

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(max_length=254)),
                ('activity_type', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('calories_burned', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'activities',
            },
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_name', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=100)),
                ('total_calories', models.IntegerField()),
                ('total_activities', models.IntegerField()),
                ('rank', models.IntegerField()),
            ],
            options={
                'db_table': 'leaderboard',
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('members', djongo.models.fields.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'teams',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('team', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('activity_type', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('difficulty', models.CharField(max_length=50)),
                ('calories_estimate', models.IntegerField()),
            ],
            options={
                'db_table': 'workouts',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='email_idx'),
        ),
    ]
